name: Fotografía
favicon: null
layout_spectrum: 0.05621396051719785
typography_spectrum: 0.3418019248638302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6699803699739277
  lightness: 0.4141972651705146
  saturation: 0.5814602212049067
  rhythmicContrast: 0.9772138257976621
purpose: []
